<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DishSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('dishes')->truncate();
        DB::table('dishes')->insert([
            [
                'id'=>1,
                'name' => 'súp lơ xanh',
                'category_id' => '1',
                'price'=>'30000',
                'image'=>'https://kokotaru.com/wp-content/uploads/image/IMG_8163.jpg',
                'kcal'=>' 31 ',
                'protein'=>'',
                'dietary_fiber'=>'',
                'carbohydrate'=>'',
                'fat'=>'',
                'vitamins'=>'',
                'minerals'=>'',
                'status'=>'',
            ],
            [
                'id'=>2,
                'name' => '',
                'category_id' => '',
                'price'=>'',
                'image'=>'',
                'kcal'=>'',
                'protein'=>'',
                'dietary_fiber'=>'',
                'carbohydrate'=>'',
                'fat'=>'',
                'vitamins'=>'',
                'minerals'=>'',
                'status'=>'',
            ],
            [
                'id'=>3,
                'name' => '',
                'category_id' => '',
                'price'=>'',
                'image'=>'',
                'kcal'=>'',
                'protein'=>'',
                'dietary_fiber'=>'',
                'carbohydrate'=>'',
                'fat'=>'',
                'vitamins'=>'',
                'minerals'=>'',
                'status'=>'',
            ],
            [
                'id'=>4,
                'name' => '',
                'category_id' => '',
                'price'=>'',
                'image'=>'',
                'kcal'=>'',
                'protein'=>'',
                'dietary_fiber'=>'',
                'carbohydrate'=>'',
                'fat'=>'',
                'vitamins'=>'',
                'minerals'=>'',
                'status'=>'',
            ],
            [
                'id'=>5,
                'name' => '',
                'category_id' => '',
                'price'=>'',
                'image'=>'',
                'kcal'=>'',
                'protein'=>'',
                'dietary_fiber'=>'',
                'carbohydrate'=>'',
                'fat'=>'',
                'vitamins'=>'',
                'minerals'=>'',
                'status'=>'',
            ],
            [
                'id'=>6,
                'name' => '',
                'category_id' => '',
                'price'=>'',
                'image'=>'',
                'kcal'=>'',
                'protein'=>'',
                'dietary_fiber'=>'',
                'carbohydrate'=>'',
                'fat'=>'',
                'vitamins'=>'',
                'minerals'=>'',
                'status'=>'',
            ],
            [
                'id'=>7,
                'name' => '',
                'category_id' => '',
                'price'=>'',
                'image'=>'',
                'kcal'=>'',
                'protein'=>'',
                'dietary_fiber'=>'',
                'carbohydrate'=>'',
                'fat'=>'',
                'vitamins'=>'',
                'minerals'=>'',
                'status'=>'',
            ],
            [
                'id'=>8,
                'name' => '',
                'category_id' => '',
                'price'=>'',
                'image'=>'',
                'kcal'=>'',
                'protein'=>'',
                'dietary_fiber'=>'',
                'carbohydrate'=>'',
                'fat'=>'',
                'vitamins'=>'',
                'minerals'=>'',
                'status'=>'',
            ],
            [
                'id'=>9,
                'name' => '',
                'category_id' => '',
                'price'=>'',
                'image'=>'',
                'kcal'=>'',
                'protein'=>'',
                'dietary_fiber'=>'',
                'carbohydrate'=>'',
                'fat'=>'',
                'vitamins'=>'',
                'minerals'=>'',
                'status'=>'',
            ],
            [
                'id'=>10,
                'name' => '',
                'category_id' => '',
                'price'=>'',
                'image'=>'',
                'kcal'=>'',
                'protein'=>'',
                'dietary_fiber'=>'',
                'carbohydrate'=>'',
                'fat'=>'',
                'vitamins'=>'',
                'minerals'=>'',
                'status'=>'',
            ],
            [
                'id'=>11,
                'name' => '',
                'category_id' => '',
                'price'=>'',
                'image'=>'',
                'kcal'=>'',
                'protein'=>'',
                'dietary_fiber'=>'',
                'carbohydrate'=>'',
                'fat'=>'',
                'vitamins'=>'',
                'minerals'=>'',
                'status'=>'',
            ],
            [
                'id'=>12,
                'name' => '',
                'category_id' => '',
                'price'=>'',
                'image'=>'',
                'kcal'=>'',
                'protein'=>'',
                'dietary_fiber'=>'',
                'carbohydrate'=>'',
                'fat'=>'',
                'vitamins'=>'',
                'minerals'=>'',
                'status'=>'',
            ],
        ]);

    }
}
