<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FoodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('foods')->truncate();
        DB::table('foods')->insert(
            array (
                0 =>
                    array (
                        'id' => 1,
                        'name' => 'rice',
                        'price' => 1.9,
                        'image' => 'ollmonnrrofgsh3t2lpo.jpg',
                        'calo' => 1590,
                        'protein' => 2,
                        'dietary_fiber' => 69,
                        'carbohydrate' => 320,
                        'total_fat' => 98,
                        'vitamins' => 'B12,E,B6',
                        'minerals' => 'I,K,F,Se,Mn',
                    ),
                1 =>
                    array (
                        'id' => 2,
                        'name' => 'Fried rice, pickles, beef',
                        'price' => 2.8,
                        'image' => 'qdbokkbwt2xxrbwbq0gs.jpg',
                        'calo' => 2470,
                        'protein' => 0.8,
                        'dietary_fiber' => 40,
                        'carbohydrate' => 117,
                        'total_fat' => 102,
                        'vitamins' => 'C,D,B9',
                        'minerals' => 'Mg,Se,Fe,Fe,Na',
                    ),
                2 =>
                    array (
                        'id' => 3,
                        'name' => 'boiled cabbages',
                        'price' => 1.8,
                        'image' => 'w0ou4jdiuqlq1t3ehwx0.jpg',
                        'calo' => 1980,
                        'protein' => 1.4,
                        'dietary_fiber' => 66,
                        'carbohydrate' => 351,
                        'total_fat' => 50,
                        'vitamins' => 'B5,B2',
                        'minerals' => 'Cl,K,Mg',
                    ),
                3 =>
                    array (
                        'id' => 4,
                        'name' => 'Boiled Chinese cabbage',
                        'price' => 2.7,
                        'image' => 'nwansgfy24q05zcd2fye.jpg',
                        'calo' => 1940,
                        'protein' => 1.7,
                        'dietary_fiber' => 23,
                        'carbohydrate' => 424,
                        'total_fat' => 97,
                        'vitamins' => 'B6,E,B5,D,K',
                        'minerals' => 'I,Se',
                    ),
                4 =>
                    array (
                        'id' => 5,
                        'name' => 'boiled vegetables',
                        'price' => 2.9,
                        'image' => 'vth6hgtqvomngxeo3dd1.jpg',
                        'calo' => 2110,
                        'protein' => 1.8,
                        'dietary_fiber' => 74,
                        'carbohydrate' => 355,
                        'total_fat' => 86,
                        'vitamins' => 'K,B9,E,K',
                        'minerals' => 'Zn,Cu,Se,Se',
                    ),
                5 =>
                    array (
                        'id' => 6,
                        'name' => 'vegetable soup',
                        'price' => 1.1,
                        'image' => 'xky0ikudcrviztv2mhzx.jpg',
                        'calo' => 2040,
                        'protein' => 1.3,
                        'dietary_fiber' => 49,
                        'carbohydrate' => 465,
                        'total_fat' => 105,
                        'vitamins' => 'B12,B1,C,D',
                        'minerals' => 'Zn,Cr',
                    ),
                6 =>
                    array (
                        'id' => 7,
                        'name' => 'salad',
                        'price' => 2.5,
                        'image' => 'qby9srczxxhlcrziwccq.jpg',
                        'calo' => 1500,
                        'protein' => 1,
                        'dietary_fiber' => 35,
                        'carbohydrate' => 133,
                        'total_fat' => 51,
                        'vitamins' => 'B12,B12,E,K',
                        'minerals' => 'Na,K,I',
                    ),
                7 =>
                    array (
                        'id' => 8,
                        'name' => 'Five-flavored fried chicken',
                        'price' => 0.9,
                        'image' => 'xjbixmuximzwvmbwhbon.jpg',
                        'calo' => 1650,
                        'protein' => 1.5,
                        'dietary_fiber' => 21,
                        'carbohydrate' => 320,
                        'total_fat' => 37,
                        'vitamins' => 'K,B3,C,K',
                        'minerals' => 'Cl,Na,F',
                    ),
                8 =>
                    array (
                        'id' => 9,
                        'name' => 'boiled pork',
                        'price' => 2.7,
                        'image' => 'gfmwvlqfjvzd5j5guq3w.jpg',
                        'calo' => 1690,
                        'protein' => 1.5,
                        'dietary_fiber' => 48,
                        'carbohydrate' => 133,
                        'total_fat' => 59,
                        'vitamins' => 'A,B3,A,C,A',
                        'minerals' => 'Mg,Cl,Fe,Ca,F',
                    ),
                9 =>
                    array (
                        'id' => 10,
                        'name' => 'Basa Frish',
                        'price' => 0.9,
                        'image' => 'vr7ta2uxigkczs99dyrj.jpg',
                        'calo' => 1910,
                        'protein' => 1,
                        'dietary_fiber' => 48,
                        'carbohydrate' => 312,
                        'total_fat' => 78,
                        'vitamins' => 'H,K,D,B1,A',
                        'minerals' => 'K,Fe,Na',
                    ),
                10 =>
                    array (
                        'id' => 11,
                        'name' => 'Stewed pork leg with bell peppers',
                        'price' => 0.9,
                        'image' => 'ljfckfcyrgmjuexosxqi.jpg',
                        'calo' => 2670,
                        'protein' => 1.5,
                        'dietary_fiber' => 61,
                        'carbohydrate' => 483,
                        'total_fat' => 99,
                        'vitamins' => 'K,B12,B3,H,B5',
                        'minerals' => 'Zn,Fe',
                    ),
                11 =>
                    array (
                        'id' => 12,
                        'name' => 'bean sprouts',
                        'price' => 1.8,
                        'image' => 'yiqgdenawgezfklpiu6p.jpg',
                        'calo' => 2540,
                        'protein' => 1.8,
                        'dietary_fiber' => 55,
                        'carbohydrate' => 502,
                        'total_fat' => 71,
                        'vitamins' => 'B2,B2,B2,K',
                        'minerals' => 'Fe,Cr',
                    ),
                12 =>
                    array (
                        'id' => 13,
                        'name' => 'cowpea',
                        'price' => 1.1,
                        'image' => 'kifo8ntlbqxotysa271j.jpg',
                        'calo' => 2390,
                        'protein' => 1.5,
                        'dietary_fiber' => 37,
                        'carbohydrate' => 464,
                        'total_fat' => 49,
                        'vitamins' => 'B12,C,B12',
                        'minerals' => 'Se,Fe',
                    ),
                13 =>
                    array (
                        'id' => 14,
                        'name' => 'tofu in tomato sauce',
                        'price' => 2.8,
                        'image' => 'cd5jrlkareyjaullgbts.jpg',
                        'calo' => 1660,
                        'protein' => 1.9,
                        'dietary_fiber' => 56,
                        'carbohydrate' => 363,
                        'total_fat' => 56,
                        'vitamins' => 'B9,K,K,B2',
                        'minerals' => 'F,Na,Mn,Se',
                    ),
                14 =>
                    array (
                        'id' => 15,
                        'name' => 'meat stock ship',
                        'price' => 2.6,
                        'image' => 'euqvry3g5ad6fjnzzgsk.jpg',
                        'calo' => 2360,
                        'protein' => 2,
                        'dietary_fiber' => 19,
                        'carbohydrate' => 498,
                        'total_fat' => 41,
                        'vitamins' => 'H,E,A,B6,E',
                        'minerals' => 'Mn,Na,Ca,Ca,Zn',
                    ),
                15 =>
                    array (
                        'id' => 16,
                        'name' => 'meat skewer',
                        'price' => 2.4,
                        'image' => 'yiumavebo4odyujwddte.jpg',
                        'calo' => 1690,
                        'protein' => 1.1,
                        'dietary_fiber' => 63,
                        'carbohydrate' => 119,
                        'total_fat' => 96,
                        'vitamins' => 'B6,B9',
                        'minerals' => 'Cr,Ca,Fe,Cl,Zn',
                    ),
                16 =>
                    array (
                        'id' => 17,
                        'name' => 'Meat rolls',
                        'price' => 2.8,
                        'image' => 'l7tfuc6vzgmfcdswy4rm.jpg',
                        'calo' => 2280,
                        'protein' => 0.8,
                        'dietary_fiber' => 16,
                        'carbohydrate' => 473,
                        'total_fat' => 106,
                        'vitamins' => 'B1,D,K,B3',
                        'minerals' => 'Se,F,Mg',
                    ),
                17 =>
                    array (
                        'id' => 18,
                        'name' => 'sweet and sour ribs',
                        'price' => 0.7,
                        'image' => 'pn2rhxoqwpvr5qcty3ra.png',
                        'calo' => 1970,
                        'protein' => 1,
                        'dietary_fiber' => 59,
                        'carbohydrate' => 235,
                        'total_fat' => 77,
                        'vitamins' => 'B3,B2,B2',
                        'minerals' => 'Cr,Se,Na',
                    ),
                18 =>
                    array (
                        'id' => 19,
                        'name' => 'Braised fish',
                        'price' => 1.3,
                        'image' => 'dxtun4oq04v8yferh79v.png',
                        'calo' => 2120,
                        'protein' => 1.5,
                        'dietary_fiber' => 27,
                        'carbohydrate' => 390,
                        'total_fat' => 50,
                        'vitamins' => 'B6,B9',
                        'minerals' => 'Mg,F,Cu,Zn,Ca',
                    ),
                19 =>
                    array (
                        'id' => 20,
                        'name' => 'Sesame',
                        'price' => 2.1,
                        'image' => 'n6sp7zqzw0bzbt2lm7re.jpg',
                        'calo' => 1800,
                        'protein' => 1,
                        'dietary_fiber' => 41,
                        'carbohydrate' => 127,
                        'total_fat' => 35,
                        'vitamins' => 'A,C,B2,K,C',
                        'minerals' => 'I,K,Cl',
                    ),
                20 =>
                    array (
                        'id' => 21,
                        'name' => 'Brown rice',
                        'price' => 1.5,
                        'image' => 'uavculttzzphghklrms0.jpg',
                        'calo' => 2480,
                        'protein' => 0.9,
                        'dietary_fiber' => 61,
                        'carbohydrate' => 360,
                        'total_fat' => 91,
                        'vitamins' => 'B5,H',
                        'minerals' => 'I,K,K,Na',
                    ),
                21 =>
                    array (
                        'id' => 22,
                        'name' => 'Boiled cauliflower',
                        'price' => 2.5,
                        'image' => 'o9cnpgeykz83sngs1s1d.jpg',
                        'calo' => 2120,
                        'protein' => 1,
                        'dietary_fiber' => 75,
                        'carbohydrate' => 325,
                        'total_fat' => 99,
                        'vitamins' => 'B5,B3,C',
                        'minerals' => 'Cu,Mg',
                    ),
                22 =>
                    array (
                        'id' => 23,
                        'name' => 'omelet',
                        'price' => 0.5,
                        'image' => 'yddhagtnxwe0olyajvwh.jpg',
                        'calo' => 2070,
                        'protein' => 1.7,
                        'dietary_fiber' => 41,
                        'carbohydrate' => 509,
                        'total_fat' => 75,
                        'vitamins' => 'B12,B2',
                        'minerals' => 'Ca,Na,Ca,I',
                    ),
                23 =>
                    array (
                        'id' => 24,
                        'name' => 'groundnut',
                        'price' => 1.1,
                        'image' => 'lspwxz7cchuv18dfahfu.jpg',
                        'calo' => 1580,
                        'protein' => 0.8,
                        'dietary_fiber' => 39,
                        'carbohydrate' => 122,
                        'total_fat' => 71,
                        'vitamins' => 'B3,B2',
                        'minerals' => 'I,K,Na',
                    ),
                24 =>
                    array (
                        'id' => 25,
                        'name' => 'Boiled carrots',
                        'price' => 0.8,
                        'image' => 'qco0zewd4gld5iqgpxlj.jpg',
                        'calo' => 2780,
                        'protein' => 1.5,
                        'dietary_fiber' => 19,
                        'carbohydrate' => 502,
                        'total_fat' => 97,
                        'vitamins' => 'B12,C,A',
                        'minerals' => 'Cr,Mg,Mn,I',
                    ),
                25 =>
                    array (
                        'id' => 26,
                        'name' => 'boiled chicken',
                        'price' => 2.5,
                        'image' => 'twklrpvjof78m8lkabxd.jpg',
                        'calo' => 2270,
                        'protein' => 0.9,
                        'dietary_fiber' => 70,
                        'carbohydrate' => 420,
                        'total_fat' => 96,
                        'vitamins' => 'B5,B6,B9,E',
                        'minerals' => 'Fe,K,Zn,I',
                    ),
                26 =>
                    array (
                        'id' => 27,
                        'name' => 'Fried sausage',
                        'price' => 1.3,
                        'image' => 'yjxsuydaipsqudgyosoy.jpg',
                        'calo' => 2240,
                        'protein' => 1.1,
                        'dietary_fiber' => 30,
                        'carbohydrate' => 238,
                        'total_fat' => 34,
                        'vitamins' => 'K,B3,B12,B3,H',
                        'minerals' => 'Na,Mn,Mn,Na',
                    ),
                27 =>
                    array (
                        'id' => 28,
                        'name' => 'roasted meat with pan',
                        'price' => 2.1,
                        'image' => 'xscc0ekoqrgez8fq5zmb.jpg',
                        'calo' => 2330,
                        'protein' => 0.9,
                        'dietary_fiber' => 63,
                        'carbohydrate' => 110,
                        'total_fat' => 30,
                        'vitamins' => 'K,B3',
                        'minerals' => 'F,I',
                    ),
                28 =>
                    array (
                        'id' => 29,
                        'name' => 'fish fry',
                        'price' => 2.1,
                        'image' => 'bbd199qwfhnke5faorsu.jpg',
                        'calo' => 2520,
                        'protein' => 1.3,
                        'dietary_fiber' => 41,
                        'carbohydrate' => 212,
                        'total_fat' => 82,
                        'vitamins' => 'K,K,A,A',
                        'minerals' => 'I,Cr,Ca,Cr',
                    ),
                29 =>
                    array (
                        'id' => 30,
                        'name' => 'fried meat',
                        'price' => 1.1,
                        'image' => 'mfqikojoqeiprxnbeyrp.jpg',
                        'calo' => 2760,
                        'protein' => 1.1,
                        'dietary_fiber' => 51,
                        'carbohydrate' => 506,
                        'total_fat' => 77,
                        'vitamins' => 'E,E',
                        'minerals' => 'Na,I,F,Na,I',
                    ),
                30 =>
                    array (
                        'id' => 31,
                        'name' => 'kimchi',
                        'price' => 3,
                        'image' => 'uvkegromok7dfcv5wd6u.jpg',
                        'calo' => 2070,
                        'protein' => 1.7,
                        'dietary_fiber' => 31,
                        'carbohydrate' => 251,
                        'total_fat' => 42,
                        'vitamins' => 'D,H,B2,C,H',
                        'minerals' => 'F,I,Mg,Na',
                    ),
                31 =>
                    array (
                        'id' => 32,
                        'name' => 'coca',
                        'price' => 0.5,
                        'image' => 'https://kidsplaza-1.cdn.vccloud.vn/media/wysiwyg/product/be-an-be-uong/nuoc-ngot-co-ga-cocacola-nhat-160ml-1.jpg',
                        'calo' => 139,
                        'protein' => 1.7,
                        'dietary_fiber' => 31,
                        'carbohydrate' => 0,
                        'total_fat' => 42,
                        'vitamins' => 'A,C,D',
                        'minerals' => 'Na,K,Ca,C',
                    ),
                32 =>
                    array (
                        'id' => 33,
                        'name' => 'lemonade',
                        'price' => 0.5,
                        'image' => 'https://media.ex-cdn.com/EXP/media.cpcs.vn/files/f1/a799232428fa8334640045670a2cdd0b.jpg',
                        'calo' => 23,
                        'protein' => 0.4,
                        'dietary_fiber' => 2.5,
                        'carbohydrate' => 7,
                        'total_fat' => 5,
                        'vitamins' => 'A,C,E,K,B1,B2,B5,B6',
                        'minerals' => 'Ca,Fe,Mg,P,K,Na,Cu,Mn',
                    ),
                33 =>
                    array (
                        'id' => 34,
                        'name' => 'orange juice',
                        'price' => 0.5,
                        'image' => 'https://pulcinelladubai.com/wp-content/uploads/2018/12/saladfusion-orange-juice.jpg',
                        'calo' => 44,
                        'protein' => 0.7,
                        'dietary_fiber' => 2.5,
                        'carbohydrate' => 10,
                        'total_fat' => 6,
                        'vitamins' => 'A,C,D,B6,B12',
                        'minerals' => 'Ca,Fe,Mg',
                    ),
                34 =>
                    array (
                        'id' => 35,
                        'name' => 'apple juice',
                        'price' => 0.5,
                        'image' => 'https://pulcinelladubai.com/wp-content/uploads/2018/12/saladfusion-orange-juice.jpg',
                        'calo' => 45,
                        'protein' => 0.5,
                        'dietary_fiber' => 2.5,
                        'carbohydrate' => 11,
                        'total_fat' => 10,
                        'vitamins' => 'A,C,E,B1,B2,B6,K,Cu,Mn',
                        'minerals' => 'Ca,Fe,Mg',
                    ),
                35 =>
                    array (
                        'id' => 36,
                        'name' => 'mineral water',
                        'price' => 0.2,
                        'image' => 'http://sangphatwater.com/upload/sanpham/thung-nuoc-khoang-lavie-750ml-4853.jpg',
                        'calo' => 12,
                        'protein' => 0.5,
                        'dietary_fiber' => 1.5,
                        'carbohydrate' => 10,
                        'total_fat' => 10,
                        'vitamins' => 'A,C,E,B1,B2,B6,K,Cu,Mn',
                        'minerals' => 'I,Mg,K,Ca,F,Mn,Fe,Co,Cu',
                    ),
                36 =>
                    array (
                        'id' => 37,
                        'name' => 'iced tea',
                        'price' => 0.1,
                        'image' => 'https://olongha.cdn.vccloud.vn/wp-content/uploads/2018/02/IMG_7590-Copy-2808x1404.jpg',
                        'calo' => 1,
                        'protein' => 0.1,
                        'dietary_fiber' => 0.5,
                        'carbohydrate' => 10,
                        'total_fat' => 0,
                        'vitamins' => 'A,B2,B3,B5,C,E',
                        'minerals' => 'Caffeine,Enzyme,Amino acids,Polyphenols',
                    ),


            ));

    }
}
