<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FoodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('foods')->truncate();
        DB::table('foods')->insert(
            array (
                0 =>
                    array (
                        'id' => 1,
                        'name' => 'rice',
                        'category_id' => 1,
                        'price' => 30000,
                        'image' => 'ollmonnrrofgsh3t2lpo.jpg',
                        'calo' => 923.3,
                        'protein' => 23.1,
                        'dietary_fiber' => 12.2,
                        'carbohydrate' => 23.3,
                        'total_fat' => 43.23,
                        'vitamins' => 'A,C',
                        'minerals' => 'Iron,lead',
                    ),
                1 =>
                    array (
                        'id' => 2,
                        'name' => 'Fried rice, pickles, beef',
                        'category_id' => 1,
                        'price' => 30000,
                        'image' => 'qdbokkbwt2xxrbwbq0gs.jpg',
                        'calo' => 923.3,
                        'protein' => 23.1,
                        'dietary_fiber' => 12.2,
                        'carbohydrate' => 23.3,
                        'total_fat' => 43.23,
                        'vitamins' => 'A,C',
                        'minerals' => 'Iron,lead',
                    ),
                2 =>
                    array (
                        'id' => 3,
                        'name' => 'boiled cabbages',
                        'category_id' => '4',
                        'price' => 25000,
                        'image' => 'w0ou4jdiuqlq1t3ehwx0.jpg',
                        'calo' => 923.3,
                        'protein' => 23.1,
                        'dietary_fiber' => 12.2,
                        'carbohydrate' => 23.3,
                        'total_fat' => 43.23,
                        'vitamins' => 'A,C',
                        'minerals' => 'Iron,lead',
                    ),
                3 =>
                    array (
                        'id' => 4,
                        'name' => 'Boiled Chinese cabbage',
                        'category_id' => 4,
                        'price' => 25000,
                        'image' => 'nwansgfy24q05zcd2fye.jpg',
                        'calo' => 923.3,
                        'protein' => 23.1,
                        'dietary_fiber' => 12.2,
                        'carbohydrate' => 23.3,
                        'total_fat' => 43.23,
                        'vitamins' => 'A,C',
                        'minerals' => 'Iron,lead',
                    ),
                4 =>
                    array (
                        'id' => 5,
                        'name' => 'boiled vegetables',
                        'category_id' => 4,
                        'price' => 25000,
                        'image' => 'vth6hgtqvomngxeo3dd1.jpg',
                        'calo' => 923.3,
                        'protein' => 23.1,
                        'dietary_fiber' => 12.2,
                        'carbohydrate' => 23.3,
                        'total_fat' => 43.23,
                        'vitamins' => 'A,C',
                        'minerals' => 'Iron,lead',
                    ),
                5 =>
                    array (
                        'id' => 6,
                        'name' => 'vegetable soup',
                        'category_id' => 4,
                        'price' => 30000,
                        'image' => 'xky0ikudcrviztv2mhzx.jpg',
                        'calo' => 923.3,
                        'protein' => 23.1,
                        'dietary_fiber' => 12.2,
                        'carbohydrate' => 23.3,
                        'total_fat' => 43.23,
                        'vitamins' => 'A,C',
                        'minerals' => 'Iron,lead',
                    ),
                6 =>
                    array (
                        'id' => 7,
                        'name' => 'salad',
                        'category_id' => 4,
                        'price' => 20000,
                        'image' => 'qby9srczxxhlcrziwccq.jpg',
                        'calo' => 923.3,
                        'protein' => 23.1,
                        'dietary_fiber' => 12.2,
                        'carbohydrate' => 23.3,
                        'total_fat' => 43.23,
                        'vitamins' => 'A,C',
                        'minerals' => 'Iron,lead',
                    ),
                7 =>
                    array (
                        'id' => 8,
                        'name' => 'Five-flavored fried chicken',
                        'category_id' => 4,
                        'price' => 100000,
                        'image' => 'xjbixmuximzwvmbwhbon.jpg',
                        'calo' => 923.3,
                        'protein' => 23.1,
                        'dietary_fiber' => 12.2,
                        'carbohydrate' => 23.3,
                        'total_fat' => 43.23,
                        'vitamins' => 'A,C',
                        'minerals' => 'Iron,lead',
                    ),
                8 =>
                    array (
                        'id' => 9,
                        'name' => 'boiled pork',
                        'category_id' => 3,
                        'price' => 50000,
                        'image' => 'gfmwvlqfjvzd5j5guq3w.jpg',
                        'calo' => 923.3,
                        'protein' => 23.1,
                        'dietary_fiber' => 12.2,
                        'carbohydrate' => 23.3,
                        'total_fat' => 43.23,
                        'vitamins' => 'A,C',
                        'minerals' => 'Iron,lead',
                    ),
                9 =>
                    array (
                        'id' => 10,
                        'name' => 'Basa Frish',
                        'category_id' => 3,
                        'price' => 200000,
                        'image' => 'vr7ta2uxigkczs99dyrj.jpg',
                        'calo' => 923.3,
                        'protein' => 23.1,
                        'dietary_fiber' => 12.2,
                        'carbohydrate' => 23.3,
                        'total_fat' => 43.23,
                        'vitamins' => 'A,C',
                        'minerals' => 'Iron,lead',
                    ),
                10 =>
                    array (
                        'id' => 11,
                        'name' => 'Stewed pork leg with bell peppers',
                        'category_id' => 3,
                        'price' => 150000,
                        'image' => 'ljfckfcyrgmjuexosxqi.jpg',
                        'calo' => 923.3,
                        'protein' => 23.1,
                        'dietary_fiber' => 12.2,
                        'carbohydrate' => 23.3,
                        'total_fat' => 43.23,
                        'vitamins' => 'A,C',
                        'minerals' => 'Iron,lead',
                    ),
                11 =>
                    array (
                        'id' => 12,
                        'name' => 'bean sprouts',
                        'category_id' => 4,
                        'price' => 30000,
                        'image' => 'yiqgdenawgezfklpiu6p.jpg',
                        'calo' => 923.3,
                        'protein' => 23.1,
                        'dietary_fiber' => 12.2,
                        'carbohydrate' => 23.3,
                        'total_fat' => 43.23,
                        'vitamins' => 'A,C',
                        'minerals' => 'Iron,lead',
                    ),
                12 =>
                    array (
                        'id' => 13,
                        'name' => 'cowpea',
                        'category_id' => 4,
                        'price' => 30000,
                        'image' => 'kifo8ntlbqxotysa271j.jpg',
                        'calo' => 923.3,
                        'protein' => 23.1,
                        'dietary_fiber' => 12.2,
                        'carbohydrate' => 23.3,
                        'total_fat' => 43.23,
                        'vitamins' => 'A,C',
                        'minerals' => 'Iron,lead',
                    ),
                13 =>
                    array (
                        'id' => 14,
                        'name' => 'tofu in tomato sauce',
                        'category_id' => 4,
                        'price' => 30000,
                        'image' => 'cd5jrlkareyjaullgbts.jpg',
                        'calo' => 923.3,
                        'protein' => 23.1,
                        'dietary_fiber' => 12.2,
                        'carbohydrate' => 23.3,
                        'total_fat' => 43.23,
                        'vitamins' => 'A,C',
                        'minerals' => 'Iron,lead',
                    ),
                14 =>
                    array (
                        'id' => 15,
                        'name' => 'meat stock ship',
                        'category_id' => 3,
                        'price' => 100000,
                        'image' => 'euqvry3g5ad6fjnzzgsk.jpg',
                        'calo' => 923.3,
                        'protein' => 23.1,
                        'dietary_fiber' => 12.2,
                        'carbohydrate' => 23.3,
                        'total_fat' => 43.23,
                        'vitamins' => 'A,C',
                        'minerals' => 'Iron,lead',
                    ),
                15 =>
                    array (
                        'id' => 16,
                        'name' => 'meat skewer',
                        'category_id' => 3,
                        'price' => 50000,
                        'image' => 'yiumavebo4odyujwddte.jpg',
                        'calo' => 923.3,
                        'protein' => 23.1,
                        'dietary_fiber' => 12.2,
                        'carbohydrate' => 23.3,
                        'total_fat' => 43.23,
                        'vitamins' => 'A,C',
                        'minerals' => 'Iron,lead',
                    ),
                16 =>
                    array (
                        'id' => 17,
                        'name' => 'Meat rolls',
                        'category_id' => 3,
                        'price' => 40000,
                        'image' => 'l7tfuc6vzgmfcdswy4rm.jpg',
                        'calo' => 923.3,
                        'protein' => 23.1,
                        'dietary_fiber' => 12.2,
                        'carbohydrate' => 23.3,
                        'total_fat' => 43.23,
                        'vitamins' => 'A,C',
                        'minerals' => 'Iron,lead',
                    ),
                17 =>
                    array (
                        'id' => 18,
                        'name' => 'sweet and sour ribs',
                        'category_id' => 3,
                        'price' => 80000,
                        'image' => 'pn2rhxoqwpvr5qcty3ra.png',
                        'calo' => 923.3,
                        'protein' => 23.1,
                        'dietary_fiber' => 12.2,
                        'carbohydrate' => 23.3,
                        'total_fat' => 43.23,
                        'vitamins' => 'A,C',
                        'minerals' => 'Iron,lead',
                    ),
                18 =>
                    array (
                        'id' => 19,
                        'name' => 'Braised fish',
                        'category_id' => 3,
                        'price' => 150000,
                        'image' => 'dxtun4oq04v8yferh79v.png',
                        'calo' => 923.3,
                        'protein' => 23.1,
                        'dietary_fiber' => 12.2,
                        'carbohydrate' => 23.3,
                        'total_fat' => 43.23,
                        'vitamins' => 'A,C',
                        'minerals' => 'Iron,lead',
                    ),
                19 =>
                    array (
                        'id' => 20,
                        'name' => 'Sesame',
                        'category_id' => 2,
                        'price' => 10000,
                        'image' => 'n6sp7zqzw0bzbt2lm7re.jpg',
                        'calo' => 923.3,
                        'protein' => 23.1,
                        'dietary_fiber' => 12.2,
                        'carbohydrate' => 23.3,
                        'total_fat' => 43.23,
                        'vitamins' => 'A,C',
                        'minerals' => 'Iron,lead',
                    ),
                20 =>
                    array (
                        'id' => 21,
                        'name' => 'Brown rice',
                        'category_id' => 1,
                        'price' => 20000,
                        'image' => 'uavculttzzphghklrms0.jpg',
                        'calo' => 923.3,
                        'protein' => 23.1,
                        'dietary_fiber' => 12.2,
                        'carbohydrate' => 23.3,
                        'total_fat' => 43.23,
                        'vitamins' => 'A,C',
                        'minerals' => 'Iron,lead',
                    ),
                21 =>
                    array (
                        'id' => 22,
                        'name' => 'Boiled cauliflower',
                        'category_id' => 4,
                        'price' => 30000,
                        'image' => 'o9cnpgeykz83sngs1s1d.jpg',
                        'calo' => 923.3,
                        'protein' => 23.1,
                        'dietary_fiber' => 12.2,
                        'carbohydrate' => 23.3,
                        'total_fat' => 43.23,
                        'vitamins' => 'A,C',
                        'minerals' => 'Iron,lead',
                    ),
                22 =>
                    array (
                        'id' => 23,
                        'name' => 'omelet',
                        'category_id' => 3,
                        'price' => 20000,
                        'image' => 'yddhagtnxwe0olyajvwh.jpg',
                        'calo' => 923.3,
                        'protein' => 23.1,
                        'dietary_fiber' => 12.2,
                        'carbohydrate' => 23.3,
                        'total_fat' => 43.23,
                        'vitamins' => 'A,C',
                        'minerals' => 'Iron,lead',
                    ),
                23 =>
                    array (
                        'id' => 24,
                        'name' => 'groundnut',
                        'category_id' => 2,
                        'price' => 10000,
                        'image' => 'lspwxz7cchuv18dfahfu.jpg',
                        'calo' => 923.3,
                        'protein' => 23.1,
                        'dietary_fiber' => 12.2,
                        'carbohydrate' => 23.3,
                        'total_fat' => 43.23,
                        'vitamins' => 'A,C',
                        'minerals' => 'Iron,lead',
                    ),
                24 =>
                    array (
                        'id' => 25,
                        'name' => 'Boiled carrots',
                        'category_id' => 3,
                        'price' => 20000,
                        'image' => 'qco0zewd4gld5iqgpxlj.jpg',
                        'calo' => 923.3,
                        'protein' => 23.1,
                        'dietary_fiber' => 12.2,
                        'carbohydrate' => 23.3,
                        'total_fat' => 43.23,
                        'vitamins' => 'A,C',
                        'minerals' => 'Iron,lead',
                    ),
                25 =>
                    array (
                        'id' => 26,
                        'name' => 'boiled chicken',
                        'category_id' => 3,
                        'price' => 140000,
                        'image' => 'twklrpvjof78m8lkabxd.jpg',
                        'calo' => 923.3,
                        'protein' => 23.1,
                        'dietary_fiber' => 12.2,
                        'carbohydrate' => 23.3,
                        'total_fat' => 43.23,
                        'vitamins' => 'A,C',
                        'minerals' => 'Iron,lead',
                    ),
                26 =>
                    array (
                        'id' => 27,
                        'name' => 'Fried sausage',
                        'category_id' => 3,
                        'price' => 40000,
                        'image' => 'yjxsuydaipsqudgyosoy.jpg',
                        'calo' => 923.3,
                        'protein' => 23.1,
                        'dietary_fiber' => 12.2,
                        'carbohydrate' => 23.3,
                        'total_fat' => 43.23,
                        'vitamins' => 'A,C',
                        'minerals' => 'Iron,lead',
                    ),
                27 =>
                    array (
                        'id' => 28,
                        'name' => 'roasted meat with pan',
                        'category_id' => 3,
                        'price' => 60000,
                        'image' => 'xscc0ekoqrgez8fq5zmb.jpg',
                        'calo' => 923.3,
                        'protein' => 23.1,
                        'dietary_fiber' => 12.2,
                        'carbohydrate' => 23.3,
                        'total_fat' => 43.23,
                        'vitamins' => 'A,C',
                        'minerals' => 'Iron,lead',
                    ),
                28 =>
                    array (
                        'id' => 29,
                        'name' => 'fish fry',
                        'category_id' => 3,
                        'price' => 100000,
                        'image' => 'bbd199qwfhnke5faorsu.jpg',
                        'calo' => 923.3,
                        'protein' => 23.1,
                        'dietary_fiber' => 12.2,
                        'carbohydrate' => 23.3,
                        'total_fat' => 43.23,
                        'vitamins' => 'A,C',
                        'minerals' => 'Iron,lead',
                    ),
                29 =>
                    array (
                        'id' => 30,
                        'name' => 'fried meat',
                        'category_id' => 3,
                        'price' => 50000,
                        'image' => 'mfqikojoqeiprxnbeyrp.jpg',
                        'calo' => 923.3,
                        'protein' => 23.1,
                        'dietary_fiber' => 12.2,
                        'carbohydrate' => 23.3,
                        'total_fat' => 43.23,
                        'vitamins' => 'A,C',
                        'minerals' => 'Iron,lead',
                    ),
                30 =>
                    array (
                        'id' => 31,
                        'name' => 'kimchi',
                        'category_id' => 4,
                        'price' => 35000,
                        'image' => 'uvkegromok7dfcv5wd6u.jpg',
                        'calo' => 923.3,
                        'protein' => 23.1,
                        'dietary_fiber' => 12.2,
                        'carbohydrate' => 23.3,
                        'total_fat' => 43.23,
                        'vitamins' => 'A,C',
                        'minerals' => 'Iron,lead',
                    ),
            ));

    }
}
